title: Ivan Rudolph Whitlock Kruger
subtitle: A Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "https://haythamnikolaidis.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.jpg
author: Ivan Rudolph Whitlock Kruger
author_bio: >-
  Over the years I have led an accomplished career as a cross-platform mobile developer with
  9+ years’ workplace experience in building, delivering, and maintaining full-stack solutions.
  I am currently serving as a Senior Mobile Development Consultant at Tangent Solutions and
  play a vital role in the Mobile Software Development Team’s client consultations on
  Xamarin Forms, Native Android and iOS solutions. Through my commitment to this role, I
  have helped multiple clients of Tangent Solutions improve their mobile app delivery to the
  app stores and stability of their mobile applications on end-user devices.<br/><br/>
  I love technology and the possibilities that it brings. I am currently completing my B.Sc. in
  Computer Science (specialising in Game Development) at the University of London. I am an
  avid supporter of Open-Source projects and in my spare time, I build video games using
  open-source software such as Godot (game engine), Blender and Pixelorama.<br/><br/>
  I am an open communicator, a quick learner, objective, unafraid of asking questions and
  willing to look for the best-suited solutions. I understand that teamwork and cultivating a
  collaborative atmosphere is essential to a project’s ongoing success. I thrive in areas where
  innovation and creativity are a must. I am loyal and have never been afraid of hard work.
  I’m inquisitive, intelligent and relish any opportunity to fix and solve problems.<br/><br/>
  I am patient and gentle-spirited, always willing to help, although when given an opportunity,
  I can be a creative comic and a little eccentric and fun. I am widely read and knowledgeable
  about a variety of different topics. I love to explore how and why things work and place
  great value on taking enough time to make sound decisions and exploring new creative
  avenues.<br/><br/>
  My other passion projects include restoring my vintage 1969 Mini car, leading a media team
  for video production, a live band and live stream broadcasts over the weekends. I also
  collect guitars, own a few pets and a house!
author_email: "haythamnikolaidis@gmail.com"
author_location: South Africa
author_website_url: "https://haythamnikolaidis.github.io/"
typewrite-text: A multi-skilled developer from South Africa, with over 10 years development experience.
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Tangent Solutions
              company_logo: education/tangent logo.png
              company_url: https://tangentsolutions.co.za/
              designation: Senior Mobile Development Consultant
              description: As a senior consultant I bring mobile development solutions to our clients. From advocating for industry best practices to helping them implement best in class designs; my role is to help our client succeed and release their product.
              visibility: true
            - company_name: Tangent Solutions
              company_logo: education/tangent logo.png
              company_url: https://tangentsolutions.co.za/
              designation: Intermediate Software Developer
              description: 
              visibility: true
            - company_name: TomTom South Africa
              company_logo: education/TomTom-Symbol.png
              company_url: https://www.tomtom.com/en_za/
              designation: Junior Software Developer
              description: I was responsible for supporting the sales team with technical requests and in building showcases for high profile customers.
              visibility: true
            - company_name: Luminet Group
              company_logo: education/luminet_400x400.png
              company_url: 
              designation: Mobile Software Magician
              description: I was responsible for the pixie dust and rainbows that are the invisible components of a mobile app.
              visibility: true

# Education
author_education_details:
              - college_logo: education/University_of_London_coat_of_arms.svg
                college_name: University of London
                college_url: https://london.ac.uk
                college_degree: Bachelor of Science - BSc, Computer Science
                description: Bachelor of Science
                visibility: true
              - college_logo: education/vertical-up-logo-bg.png
                college_name: University of Pretoria
                college_url: https://www.up.ac.za/
                college_degree: Bachelor of Science - BSc Information Technology
                description: Bachelor of Science (B.Sc.) in Information Technology, Information and Knowledge System
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: projects/outsurance.webp
                project_title: OUTsurance Mobile App
                project_description: The OUTsurance app allows you to check your insurance policy information including the date and amount of your next OUTbonus payment.
                project_url: https://play.google.com/store/apps/details?id=za.co.outsurance&hl=en_ZA&gl=US
                visibility: true
              - project_thumbnail: 
                project_title: Brandworx Mobile App
                project_description: A cross platform application build using Xamarin
                project_url: https://tangentsolutions.co.za/case_studies/brandworx-2021/
                visibility: true

# social links
twitter_username: IvanKrug3r
github_username:  haythamnikolaidis
# facebook_username: johndoe
linkedin_username: ivan-kruger
# behance_username: johndoe
# instagram_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
# formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
# olvy_organization: devlopr
# olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
